// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace gRPC.Message {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgxnUlBDLk1lc3NhZ2UaDW1lc3NhZ2UucHJvdG8y",
            "kQEKC2dSUENTZXJ2aWNlEj4KCFNheUhlbGxvEhouZ1JQQy5NZXNzYWdlLkhl",
            "bGxvUmVxdWVzdBoWLmdSUEMuTWVzc2FnZS5SZXNwb25zZRJCCgpTYXlHb29k",
            "YnllEhwuZ1JQQy5NZXNzYWdlLkdvb2RCeWVSZXF1ZXN0GhYuZ1JQQy5NZXNz",
            "YWdlLlJlc3BvbnNlQg+qAgxnUlBDLk1lc3NhZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::gRPC.Message.MessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
